# Include the .env file if it exists
-include .env
export

.PHONY: help env lint lint-fix format format-check quality install-hooks run test
.PHONY: build-up up down clean docker-logs
.PHONY: migration migrate downgrade migration-history migration-current

help:
	## Show available Makefile commands
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<command>\033[0m\n\nCommands:\n"} \
		/^[a-zA-Z_-]+:.*?##/ {printf "  \033[36m%-24s\033[0m %s\n", $$1, $$2}' \
		$(MAKEFILE_LIST)


env:	## Copy the example environment file to a real .env file
	@if [ ! -f .env ]; then cp .env.example .env && echo "Created .env from .env.example";fi

# uv commands
lint:	## Run Ruff linting and automatically fix issues
	uv run ruff check . --fix

lint-check:	## Run Ruff linting without changes
	uv run ruff check .

format:	## Run Ruff formatting
	uv run ruff format .

format-check:	## Check formatting without changes
	uv run ruff format --check .

quality:	## Run all code quality checks
	make lint-check
	make format-check

ruff:	## Apply ruff linting and formatting to current directory
	make lint
	make format

install-hooks:	## Install git pre-commit hooks
	uv run pre-commit install

run:	## Run the api server
	uv run uvicorn app.main:app

test:	## Run the test suite
	uv run pytest


# Docker commands
up:	## Start Docker services (in detached mode)
	docker compose up -d

build-up:	## Build Docker image and start Docker services
	docker compose up --build

down:	## Remove Docker services and networks
	docker compose down

clean:	## Remove Docker services, networks, and volumes
	docker compose down -v

docker-logs:	## View Docker logs
	docker compose logs -f


# Load .env, replace Docker's database hostname with localhost.
define set-local-db-url
	@set -a; \
	. ./.env; \
	set +a; \
	HOST_DATABASE_URL="$$(printf '%s' "$$DATABASE_URL" | sed 's/@db:/@localhost:/')"; \
	DATABASE_URL="$$HOST_DATABASE_URL"
endef

# Alembic commands
migration: env	## Create a new autogenerated migration (requires message="...")
	@$(call set-local-db-url); \
	uv run alembic revision --autogenerate -m "$(message)"

migrate: env	## Apply all pending database migrations
	@$(call set-local-db-url); \
	uv run alembic upgrade head

downgrade: env	## Downgrade the database by one migration
	@$(call set-local-db-url); \
	uv run alembic downgrade -1

migration-history: env	## Show the complete migration history
	@$(call set-local-db-url); \
	uv run alembic history --verbose

migration-current: env	## Show the database's current migration revision
	@$(call set-local-db-url); \
	uv run alembic current
